### ISSUE TITLE
Error in curl::curl_fetch_memory(url, handle = handle): Could not resolve host: 32001E0555

### ISSUE THREAD

**Issue by williamrohdemadsen** [michalovadek/eurlex#14]
I am suddenly getting a weird problem after using the `eurlex` package for a few months. When I run the `elx_fetch_data()` function, I get the following error:

`Error in curl::curl_fetch_memory(url, handle = handle): Could not resolve host: 32001E0555`

Reprex:
```
# Load package
library(eurlex)

# Run function
elx_fetch_data("32001E0555", "title")
```

Thanks for all your work. Amazing package.

On another note, is it possible to gather the **CELEX** IDs for **all acts in a given directory coder**, e.g. **CC = 18 which is Common Foreign and Security Policy**, via **REST** instead of SPARQL?
Directory code CC = 18 is Common Foreign and Security Policy.

**Comment by michalovadek** [comment]
You need to specify the full url like so:

`elx_fetch_data(url = "http://publications.europa.eu/resource/celex/32001E0555", type = "title")`

As for your second question, this is probably possible but I haven't looked into anything like that. SPARQL is also just faster in general, so I focused most of my attention there. Happy to receive a pull request or suggestion if you figure it out.

**Comment by williamrohdemadsen** [comment]
Awesome, thanks!
