### ISSUE TITLE
Query result are limited to 10e6

### ISSUE THREAD

**Issue by michelemaroni** [michalovadek/eurlex#17]
Dear Michal,

Thank you for developing such a useful package, writing useful and clear documentation, and also congratulation for the very interesting article published in Political Research Exchange.

I tried you package and a noticed that when I run a large query the results are limited to 10e6 rows. Is there a way to resolve this limit?

A reproducible example is provided here:
"
      library(eurlex)
      library(dplyr)
      library(ggplot2)      
      legal <- elx_make_query(resource_type = "any",  sector = 3,
                             include_celex = TRUE, include_force = TRUE,
                             include_date = TRUE, include_date_force = TRUE,
                             include_date_endvalid = TRUE, include_eurovoc = TRUE, 
                             include_directory = TRUE, include_citations = TRUE) %>% 
        elx_run_query()      
      preparatory <- elx_make_query(resource_type = "any",  sector = 5,
                              include_celex = TRUE, include_date = TRUE,
                              include_eurovoc = TRUE, include_directory = TRUE, 
                              include_citations = TRUE) %>% 
        elx_run_query()      
      dat <- as_tibble(data.frame(X=rep(0, 16000000),y=rep(0, 16000000),z=rep(0, 16000000)))
"

I provide you also with the sessionInfo output
"
      > sessionInfo()
      R version 4.0.2 (2020-06-22)
      Platform: x86_64-w64-mingw32/x64 (64-bit)
      Running under: Windows 10 x64 (build 19042)      
      Matrix products: default      
      locale:
      [1] LC_COLLATE=Italian_Italy.1252  LC_CTYPE=Italian_Italy.1252    LC_MONETARY=Italian_Italy.1252
      [4] LC_NUMERIC=C                   LC_TIME=Italian_Italy.1252    
      
      attached base packages:
      [1] stats     graphics  grDevices utils     datasets  methods   base     
      
      other attached packages:
      [1] ggplot2_3.3.3        dplyr_1.0.5          eurlex_0.3.5         RevoUtils_11.0.2     RevoUtilsMath_11.0.0
      
      loaded via a namespace (and not attached):
       [1] rstudioapi_0.11  xml2_1.3.2       magrittr_1.5     tidyselect_1.1.0 munsell_0.5.0    colorspace_2.0-0
       [7] R6_2.4.1         rlang_0.4.10     httr_1.4.1       tools_4.0.2      grid_4.0.2       gtable_0.3.0    
      [13] withr_2.2.0      ellipsis_0.3.1   digest_0.6.25    tibble_3.0.2     lifecycle_1.0.0  crayon_1.3.4    
      [19] farver_2.1.0     tidyr_1.1.3      purrr_0.3.4      vctrs_0.3.7      curl_4.3         glue_1.4.1      
      [25] compiler_4.0.2   pillar_1.4.6     generics_0.1.0   scales_1.1.1     pkgconfig_2.0.3 
"

Another very useful feature would the possibility to define a start date and an end date for the query.

Thank you once again.

Best regards.

**Comment by michalovadek** [comment]
thanks for bringing this to my attention. The code runs the same way for me, so my best hunch at the moment is that SPARQL responses are capped at 1 million rows. Not sure at the moment how to solve this sustainably, but what you can always do is request the data in smaller batches. There are less than 1mil unique identifiers in the sectors you are requesting, so if you specify the resource types individually, you will be able to get all your data. For example something like this:

```
library(tidyverse)

sec_5_q <- "PREFIX cdm: <http://publications.europa.eu/ontology/cdm#>
  PREFIX annot: <http://publications.europa.eu/ontology/annotation#>
  PREFIX skos:<http://www.w3.org/2004/02/skos/core#>
  PREFIX dc:<http://purl.org/dc/elements/1.1/>
  PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
  PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
  PREFIX owl:<http://www.w3.org/2002/07/owl#>
  select distinct ?work ?type ?celex where{
    ?work cdm:resource_legal_id_sector ?sector.
    FILTER(str(?sector)='5')
 FILTER not exists{?work cdm:work_has_resource-type <http://publications.europa.eu/resource/authority/resource-type/CORRIGENDUM>}
 OPTIONAL{?work cdm:resource_legal_id_celex ?celex.}
 OPTIONAL{?work cdm:work_has_resource-type ?type.}}" %>% 
     elx_run_query()

sec_5_types <- sec_5_q %>%
 distinct(type) %>% 
 deframe() %>%
 str_remove("http://publications.europa.eu/resource/authority/resource-type/")

l <- list()

for (i in 1:length(sec_5_types){

  l[[i]] <- elx_make_query("manual", manual_type = sec_5_types[i],
                               include_celex = TRUE, include_force = TRUE,
                               include_date = TRUE, include_date_force = TRUE,
                               include_date_endvalid = TRUE, include_eurovoc = TRUE,
                               include_directory = TRUE, include_citations = TRUE) %>%
     elx_run_query()

}


```

Note that I don't actually recommend downloading all the variables in one query (due to NAs and observations that are not uniquely identified) but that's your call. You are also likely to get much better execution times if you separate the variables into individual queries and merge them afterwards. You can look at the example in the Github readme.

**Comment by michalovadek** [comment]
since `eurlex` now supports sector-specific SPARQL queries, I will close this, though the results being capped at 10e6 is still an issue
