### ISSUE TITLE
Proposal for enchancements of elx_fetch_data

### ISSUE THREAD

**Issue by michelemaroni** [michalovadek/eurlex#20]
Dear Michal,

I use eurlex package on a regular basis to extract EU policy documents
with the purspose of mapping of terms related to UN 2030 SDGs in theese EU policy documents.
I use elx_fetch_data to batch dowload the raw text of the documents.

I would like to propose tow enhancements for this function:
1) Rather than return just the 'out' for the type of resource requested, the function could return the 'out' and the code of the HTTP request for a resource type. The function returns a named list where the first element is 'out' and the second the HTTP code.
This would allow to easily check if a resource was not retrieved, which is useful when dealing with a large number of documents.

2) Insert the document XML notice among the resource type option.
This could be an useful and efficient way to get a plethora of information for each document. The xml could be then parsed locally to extract data of interest like directory codes, the subject matter, the instruments cited, related documents etc.
In many cases it might be easier and faster to work with the XML notice than to develop and run a (complex) SPARQL query.
For an easier implementation, this option could ignore the language paramenters, so that one would get the document xml notice the same way is obtained from eurlex.

What do you think about theese enhancements, would it be difficult to implement them?

Once again, many thanks for developing and releasing such a useful and easy to use package.

Many thanks and have a nice day.

Best

**Comment by michalovadek** [comment]
Hi Michele,

I am glad the package is of use (I still use it myself).

1. elx_fetch_date() does check the http status code of the returned object before parsing, so in principle this should be taken care of, but I see that the code is not really robust. I will have a look at this and see what can be done.
2. So if I understand correctly you would like to return just the entire XML notice? I suppose this should be possible but I need to look at how to do it. There might be some xml pointer pitfall to deal with.

I was planning a smaller update to the package anyway; I will push some code to the devel branch here and would appreciate if you could test out the features.

**Comment by michalovadek** [comment]
hey, so I wrote some code to the effect of what you were asking for. Can you please install the version on Github and try it out? Let me know if elx_download_xml() is more or less what you expected under 2). I also tightened the error checking for http requests, so elx_fetch_data should simply fail when there is a server/internet/wrong url problem. I prefer this over returning the request, since that increases the resulting object (= slows the function down), but it's possible that this could be improved further

**Comment by michelemaroni** [comment]
Hi Michal,

Thank you very much for the quick reaction.
I am veary curious to test the new version,
but there is an issues when i try to install from github (see screenshot in the attachment).
![2022-01-28 12_28_08-Window](https://user-images.githubusercontent.com/35966074/151539433-b67e3b6d-7499-49e5-96c0-aa2c58ba2be5.png)
Did you meant to use %>% for chaining operations maybe or is it somethingg related to my local settings?

I had however a look at the source of the functions, and I can give already some feedback and a question:
2) In eurlex/R/elx_download_xml.R it is a very good choice to allow both branch and object to be used.
I made some test between the different options descrbed in the " [Cellar The semantic repository of the Publications Office](https://data.europa.eu/doi/10.2830/03072)" and i figured out that the 'object' may be what works best for me. However other user may have different needs. Would it make sense to you to allow all the options described on page 31?

1) It is reasonable to have an exception when calling elx_fetch_data gets a bad HTTP request, but could this behavior be overridden by the user?
To be clearer, a 'raise_exception' boolean parameter could be passed by the user so that he/she can decide wheter the execution of their code should stop or not. The case would be that you are maybe repeatedly calling the function in a loop/mapply and you would like the code to keep running even in case of a bad request.

Many thanks, and i'll definitely try the new features as soon as the installation issues is fixed.

Have a nice day!

**Comment by michalovadek** [comment]
Can you please check what version of R you are using? I started to substitute the magrittr pipe for the native pipe (`|>`) to cut down on dependencies but if you have an older version of R this will not work. I may need to hold off these changes then anyway for the moment to ensure backwards compatibility (but I do recommend updating R at this point).

1. if you want errors to not interrupt your loops you should use tryCatch() or purrr::possibly(). The errors that I implemented are now also required by CRAN policy
2. good suggestion. I added options for all notices described in the documentation, except RDF objects. Identifiers can be retrieved with `elx_fetch_data(type = "ids")`

I would appreciate if you tried again the new code uploaded to the Github devel branch

**Comment by michelemaroni** [comment]
> Can you please check what version of R you are using? I started to substitute the magrittr pipe for the native pipe (`|>`) to cut down on dependencies but if you have an older version of R this will not work. I may need to hold off these changes then anyway for the moment to ensure backwards compatibility (but I do recommend updating R at this point).

Indeed, I am using Microsoft R Open 4.0.2. The base R pipe operator comes from 4.1.0

> 1. if you want errors to not interrupt your loops you should use tryCatch() or purrr::possibly(). The errors that I implemented are now also required by CRAN policy

Good suggestion, I can just write a wrapper function that has the exception handling. Thanks

> 2. good suggestion. I added options for all notices described in the documentation, except RDF objects. Identifiers can be retrieved with `elx_fetch_data(type = "ids")`

Thanks.

> I would appreciate if you tried again the new code uploaded to the Github devel branch

Sure will do and give you feedback in the next days.
Thanks again and have a nice day.
