### ISSUE TITLE
Council votes on legislative acts

### ISSUE THREAD

**Issue by momamu** [michalovadek/eurlex#6]
Is it also possible to access the Council votes on legislative acts?

**Comment by michalovadek** [comment]
as far as I know, this is not currently possible within EurLex (happy to be corrected), but some structured data is made available through the Council website. I will try to investigate at some point whether a separate API could be built for that.

**Comment by michalovadek** [comment]
I experimented a bit with the SPARQL endpoint made available by the EU Council and there might be a way forward. However, I have experienced some problems with the endpoint, which currently prevent deployment of the code. I will try to reach out to the administrators and see whether we can make this work.

**Comment by michalovadek** [comment]
Thanks to [singuch](https://github.com/singuch), the next release of eurlex is going to have a function for downloading Council votes.
